# Statistical Methods in Pandas - Lab

## Introduction

In this lab you'll get some hands-on experience using some of the key summary statistics methods in Pandas.

## Objectives
You will be able to:

- Calculate summary statistics for a series and DataFrame 
- Use the `.apply()` or `.applymap()` methods to apply a function to a pandas series or DataFrame  


## Getting Started

For this lab, we'll be working with a dataset containing information on various lego datasets. You will find this dataset in the file `'lego_sets.csv'`.   

In the cell below:

- Import Pandas and set the standard alias of `pd`
- Import the `'lego_sets.csv'` dataset 
- Display the first five rows of the DataFrame to get a feel for what we'll be working with

In [2]:
# Import pandas
import pandas as pd

# Import the 'lego_sets.csv' dataset
df = pd.read_csv('lego_sets.csv')

# Print the first five rows of DataFrame
df.head()

,ages,list_price,num_reviews,piece_count,play_star_rating,prod_desc,prod_id,prod_long_desc,review_difficulty,set_name,star_rating,theme_name,val_star_rating,country
0,6-12,29.99,2.0,277.0,4.0,Catapult into action and take back the eggs fr...,75823.0,Use the staircase catapult to launch Red into ...,Average,Bird Island Egg Heist,4.5,Angry Birds™,4.0,US
1,6-12,19.99,2.0,168.0,4.0,Launch a flying attack and rescue the eggs fro...,75822.0,Pilot Pig has taken off from Bird Island with ...,Easy,Piggy Plane Attack,5.0,Angry Birds™,4.0,US
2,6-12,12.99,11.0,74.0,4.3,Chase the piggy with lightning-fast Chuck and ...,75821.0,Pitch speedy bird Chuck against the Piggy Car....,Easy,Piggy Car Escape,4.3,Angry Birds™,4.1,US
3,12+,99.99,23.0,1032.0,3.6,Explore the architecture of the United States ...,21030.0,Discover the architectural secrets of the icon...,Average,United States Capitol Building,4.6,Architecture,4.3,US
4,12+,79.99,14.0,744.0,3.2,Recreate the Solomon R. Guggenheim Museum® wit...,21035.0,Discover the architectural secrets of Frank Ll...,Challenging,Solomon R. Guggenheim Museum®,4.6,Architecture,4.1,US

## Getting DataFrame-Level Statistics

We'll begin by getting some overall summary statistics on the dataset. There are two ways we'll get this information -- `.info()` and `.describe()`.

The `.info()` method provides us metadata on the DataFrame itself. This allows us to answer questions such as:

* What data type does each column contain?
* How many rows are in my dataset? 
* How many total non-missing values does each column contain?
* How much memory does the DataFrame take up?

In the cell below, call our DataFrame's `.info()` method.

In [3]:
# Call the .info() method
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ages               12261 non-null  object
 1   list_price         12261 non-null  float64
 2   num_reviews        10641 non-null  float64
 3   piece_count        12261 non-null  float64
 4   play_star_rating   10486 non-null  float64
 5   prod_desc          11884 non-null  object
 6   prod_id            12261 non-null  float64
 7   prod_long_desc     12261 non-null  object
 8   review_difficulty  10206 non-null  object
 9   set_name           12261 non-null  object
 10  star_rating        10641 non-null  float64
 11  theme_name         12258 non-null  object
 12  val_star_rating    10466 non-null  float64
 13  country            12261 non-null  object
dtypes: float64(7), object(7)
memory usage: 1.3+ MB

#### Interpreting the Results

Read the output above, and then answer the following questions:

- How many total rows are in this DataFrame?  
- How many columns contain numeric data? 
- How many contain categorical data? 
- Identify at least 3 columns that contain missing values. 

Write your answer below this line:
________________________________________________________________________________________________________________________________

Whereas `.info()` provides statistics about the DataFrame itself, `.describe()` returns output containing basic summary statistics about the data contained with the DataFrame.  

In the cell below, call the DataFrame's `.describe()` method.

In [4]:
# Call the .describe() method
df.describe()

,list_price,num_reviews,piece_count,play_star_rating,prod_id,star_rating,val_star_rating
count,12261.000000,10641.000000,12261.000000,10486.000000,1.226100e+04,10641.000000,10466.000000
mean,65.141998,16.826238,493.405921,4.337641,5.983675e+04,4.514134,4.228960
std,91.980429,36.368984,825.364580,0.652051,1.638115e+05,0.518865,0.660282
min,2.272400,1.000000,1.000000,1.000000,6.300000e+02,1.800000,1.000000
25%,19.990000,2.000000,97.000000,4.000000,2.103400e+04,4.300000,4.000000
50%,36.587800,6.000000,216.000000,4.500000,4.206900e+04,4.700000,4.300000
75%,70.192200,13.000000,544.000000,4.800000,7.092200e+04,5.000000,4.700000
max,1104.870000,367.000000,7541.000000,5.000000,2.000431e+06,5.000000,5.000000

#### Interpreting the Results

The output contains descriptive statistics corresponding to the columns. Use these to answer the following questions:

- How much is the standard deviation for `piece count`? 
- How many pieces are in the largest lego set?
- How many in the smallest lego set? What is the median `val_star_rating`?

________________________________________________________________________________________________________________________________

## Getting Summary Statistics

Pandas also allows us to easily compute individual summary statistics using built-in methods.  Next, we'll get some practice using these methods. 

In the cell below, compute the median value of the `star_rating` column.

In [5]:
# Calculate the median of the star_rating column
df['star_rating'].median()

4.7

Next, get a count of the total number of unique values in `play_star_rating`.

In [6]:
# Print the number of unique values in play_star_rating
df['play_star_rating'].unique()

array([4. , 4.3, 3.6, 3.2, 3.7, 4.4, 4.1, 4.2, 3.8, 4.7, 3. , 5. , 2. ,
       nan, 4.6, 2.7, 4.5, 1. , 3.5, 3.3, 3.9, 4.8, 2.9, 3.4, 4.9, 2.5,
       2.2, 2.3, 2.8, 3.1, 2.1])

Now, compute the standard deviation of the `list_price` column.

In [7]:
# Calculate the standard deviation of the list_price column
df['list_price'].std()

91.9804293059243

If we bought every single lego set in this dataset, how many pieces would we have?  

> **Note**: If you truly want to answer this accurately, and are up for the challenge, remove duplicate lego-set entries before summing the pieces. That is, many of the lego sets are listed multiple times in the dataset above, depending on the country where it is being sold and other unique parameters. If you're stuck, just practice calculating the total number of pieces in the dataset for now.

### provided solution

In [40]:
# Total number of pieces across all unique Lego sets
df.drop_duplicates('prod_id')['piece_count'].sum()

319071.0

### my attempt

In [26]:
df.groupby('prod_id')['piece_count'].unique().sum()[1]

319073.0

###### why the diffrence?

- steps

In [37]:
df['prod_id'].unique()

array([7.582300e+04, 7.582200e+04, 7.582100e+04, 2.103000e+04,
       2.103500e+04, 2.103900e+04, 2.102800e+04, 2.102900e+04,
       2.103400e+04, 2.103300e+04, 2.103600e+04, 2.101900e+04,
       2.103200e+04, 1.710100e+04, 4.159700e+04, 4.161400e+04,
       4.161300e+04, 4.160900e+04, 4.160800e+04, 4.160400e+04,
       4.160500e+04, 4.160600e+04, 4.160700e+04, 4.148500e+04,
       4.027000e+04, 4.159900e+04, 4.159800e+04, 4.160300e+04,
       4.160200e+04, 4.160000e+04, 4.160100e+04, 4.161100e+04,
       4.161000e+04, 4.027100e+04, 4.148700e+04, 4.148800e+04,
       4.159400e+04, 4.148600e+04, 4.158500e+04, 4.159000e+04,
       4.159300e+04, 4.159200e+04, 4.159500e+04, 4.159600e+04,
       4.158800e+04, 4.159100e+04, 4.158700e+04, 4.158600e+04,
       6.017500e+04, 6.005200e+04, 6.005100e+04, 6.016200e+04,
       6.016700e+04, 6.016100e+04, 6.014100e+04, 6.018800e+04,
       6.011000e+04, 6.017400e+04, 6.016900e+04, 6.014000e+04,
       6.016000e+04, 6.017300e+04, 6.016600e+04, 6.013900e+04,
       6.015400e+04, 6.018600e+04, 6.015300e+04, 6.013800e+04,
       6.016500e+04, 6.017200e+04, 6.015900e+04, 6.010800e+04,
       6.018200e+04, 6.018300e+04, 6.010700e+04, 6.018000e+04,
       6.015000e+04, 7.499000e+03, 6.014800e+04, 6.017900e+04,
       6.018100e+04, 6.013700e+04, 6.017600e+04, 6.018500e+04,
       1.075100e+04, 6.016400e+04, 6.015800e+04, 7.895000e+03,
       7.280000e+03, 7.281000e+03, 6.017700e+04, 6.015700e+04,
       1.075000e+04, 6.016300e+04, 6.017100e+04, 6.018400e+04,
       6.017800e+04, 6.017000e+04, 6.015600e+04, 6.013400e+04,
       6.012500e+04, 6.012400e+04, 6.010900e+04, 6.014300e+04,
       6.012900e+04, 6.012300e+04, 6.012200e+04, 6.011900e+04,
       6.016800e+04, 6.015500e+04, 6.010100e+04, 6.012100e+04,
       6.011700e+04, 6.014200e+04, 6.013600e+04, 6.014600e+04,
       6.014500e+04, 6.012000e+04, 6.010000e+04, 6.010600e+04,
       6.013500e+04, 1.069800e+04, 1.069600e+04, 1.071300e+04,
       1.069300e+04, 1.069200e+04, 1.070100e+04, 1.071400e+04,
       1.070000e+04, 1.070600e+04, 1.070800e+04, 1.070700e+04,
       1.070900e+04, 6.300000e+02, 1.069400e+04, 1.069900e+04,
       3.106900e+04, 3.107000e+04, 3.108100e+04, 3.107900e+04,
       3.108000e+04, 3.106600e+04, 3.106800e+04, 3.106700e+04,
       3.106200e+04, 3.107400e+04, 3.107600e+04, 3.107500e+04,
       3.105800e+04, 3.107300e+04, 3.105600e+04, 3.105700e+04,
       3.107100e+04, 3.107200e+04, 3.104600e+04, 3.105900e+04,
       3.105100e+04, 3.106400e+04, 3.103500e+04, 3.106300e+04,
       3.104900e+04, 3.104700e+04, 3.106000e+04, 3.104300e+04,
       3.102900e+04, 1.025600e+04, 1.026000e+04, 1.025900e+04,
       1.025500e+04, 1.025300e+04, 1.021400e+04, 1.025700e+04,
       1.024700e+04, 1.025100e+04, 1.024300e+04, 1.024600e+04,
       1.025800e+04, 1.022000e+04, 1.025200e+04, 1.024200e+04,
       1.025400e+04, 7.092200e+04, 7.608700e+04, 7.117100e+04,
       7.092300e+04, 7.608600e+04, 7.092100e+04, 7.609700e+04,
       7.609800e+04, 7.091900e+04, 7.092000e+04, 1.075300e+04,
       7.091800e+04, 7.608500e+04, 7.609600e+04, 4.123200e+04,
       4.123000e+04, 4.123100e+04, 4.123300e+04, 7.605200e+04,
       4.123900e+04, 7.605500e+04, 7.605400e+04, 4.123800e+04,
       4.123700e+04, 7.604500e+04, 7.607500e+04, 7.605600e+04,
       7.602500e+04, 4.123400e+04, 7.604400e+04, 7.606800e+04,
       7.606900e+04, 7.607000e+04, 7.128700e+04, 7.134300e+04,
       7.134600e+04, 7.134900e+04, 7.125500e+04, 7.124200e+04,
       7.126400e+04, 7.126700e+04, 7.124800e+04, 7.122900e+04,
       7.123500e+04, 7.134800e+04, 7.126600e+04, 7.123800e+04,
       7.121800e+04, 7.123200e+04, 7.104000e+04, 7.104200e+04,
       4.114800e+04, 4.115400e+04, 4.115300e+04, 4.115000e+04,
       4.115200e+04, 4.114600e+04, 1.074400e+04, 4.114500e+04,
       1.073600e+04, 1.074300e+04, 1.074200e+04, 4.115500e+04,
       4.115100e+04, 1.073000e+04, 1.073300e+04, 4.030700e+04,
       4.038800e+04, 1.073200e+04, 1.073100e+04, 4.106600e+04,
       4.114900e+04, 4.114200e+04, 4.114700e+04, 4.114400e+04,
       4.114300e+04, 1.088000e+04, 1.087900e+04, 1.050800e+04,
       1.080500e+04, 1.084000e+04, 1.086900e+04, 1.083600e+04,
       1.081300e+04, 1.086400e+04, 1.050700e+04, 1.083500e+04,
       1.084400e+04, 1.084100e+04, 1.084600e+04, 1.082700e+04,
       1.083400e+04, 1.082300e+04, 1.085700e+04, 1.083700e+04,
       1.087600e+04, 1.086300e+04, 1.087800e+04, 1.086800e+04,
       1.086500e+04, 1.057200e+04, 1.059200e+04, 1.059700e+04,
       1.083900e+04, 1.084500e+04, 1.087100e+04, 1.083300e+04,
       1.084700e+04, 1.081600e+04, 1.081200e+04, 1.085600e+04,
       1.086700e+04, 1.087700e+04, 1.086100e+04, 1.084300e+04,
       1.083200e+04, 1.080900e+04, 1.086200e+04, 2.304000e+03,
       1.083800e+04, 1.087000e+04, 1.085800e+04, 1.085100e+04,
       1.085900e+04, 1.086000e+04, 1.060800e+04, 1.060700e+04,
       1.082000e+04, 1.080400e+04, 1.085500e+04, 1.060600e+04,
       1.082200e+04, 1.081700e+04, 1.082800e+04, 1.059000e+04,
       1.061600e+04, 1.081800e+04, 1.061500e+04, 1.080100e+04,
       1.080800e+04, 1.083100e+04, 1.084900e+04, 1.085200e+04,
       1.085000e+04, 4.118800e+04, 4.119400e+04, 4.118700e+04,
       4.119300e+04, 4.118300e+04, 4.119200e+04, 4.119100e+04,
       4.118600e+04, 4.119000e+04, 4.118500e+04, 4.118100e+04,
       4.118200e+04, 4.131800e+04, 4.131400e+04, 4.131700e+04,
       4.134000e+04, 4.132400e+04, 4.133900e+04, 4.131300e+04,
       4.133800e+04, 4.132000e+04, 4.132300e+04, 4.132500e+04,
       4.133600e+04, 4.133500e+04, 4.132200e+04, 4.131600e+04,
       4.131100e+04, 4.131900e+04, 4.133400e+04, 4.133300e+04,
       4.133200e+04, 1.074900e+04, 4.131500e+04, 4.133000e+04,
       4.132900e+04, 1.074800e+04, 4.132800e+04, 4.132700e+04,
       4.017100e+04, 4.112400e+04, 4.113200e+04, 4.112800e+04,
       4.130300e+04, 4.113000e+04, 4.113400e+04, 4.112600e+04,
       4.131200e+04, 4.132600e+04, 4.130000e+04, 4.131000e+04,
       4.130100e+04, 4.112700e+04, 4.130600e+04, 4.130900e+04,
       4.112300e+04, 4.130200e+04, 7.582700e+04, 7.582800e+04,
       2.131300e+04, 2.131400e+04, 2.131000e+04, 2.130900e+04,
       2.130800e+04, 2.131200e+04, 2.130700e+04, 1.075800e+04,
       1.076100e+04, 1.075700e+04, 1.076000e+04, 1.075600e+04,
       1.075900e+04, 1.074500e+04, 1.073400e+04, 1.074600e+04,
       1.075400e+04, 1.073900e+04, 1.074000e+04, 1.075500e+04,
       1.073800e+04, 1.073700e+04, 1.074700e+04, 1.068700e+04,
       1.072500e+04, 1.073500e+04, 1.072200e+04, 1.072600e+04,
       1.072300e+04, 1.072000e+04, 7.593000e+04, 7.592900e+04,
       7.593300e+04, 7.593200e+04, 7.593100e+04, 7.592800e+04,
       7.592700e+04, 7.592600e+04, 7.610500e+04, 7.610800e+04,
       7.610700e+04, 7.610300e+04, 7.610400e+04, 7.610200e+04,
       7.610100e+04, 7.608800e+04, 7.607800e+04, 7.608400e+04,
       7.608300e+04, 7.610000e+04, 7.607700e+04, 7.609900e+04,
       7.608200e+04, 7.607600e+04, 7.609100e+04, 7.609000e+04,
       7.608900e+04, 7.607100e+04, 7.608000e+04, 7.606700e+04,
       7.606000e+04, 7.607900e+04, 7.602900e+04, 7.607200e+04,
       7.607300e+04, 3.131300e+04, 4.550000e+04, 4.550100e+04,
       4.550600e+04, 4.550500e+04, 4.550900e+04, 4.550800e+04,
       4.551700e+04, 4.550200e+04, 4.550300e+04, 4.550700e+04,
       4.551400e+04, 4.550400e+04, 2.113700e+04, 2.113600e+04,
       2.113400e+04, 2.113500e+04, 2.114400e+04, 2.114300e+04,
       2.114200e+04, 2.113000e+04, 2.114000e+04, 2.114100e+04,
       2.112300e+04, 2.112900e+04, 2.113900e+04, 2.113800e+04,
       2.112200e+04, 2.112500e+04, 2.112400e+04, 2.112100e+04,
       2.112600e+04, 2.111900e+04, 7.102100e+04, 7.102000e+04,
       7.101900e+04, 7.101800e+04, 7.035700e+04, 7.200600e+04,
       7.200500e+04, 7.200400e+04, 7.200300e+04, 7.200200e+04,
       7.200100e+04, 7.035800e+04, 7.036500e+04, 7.034700e+04,
       7.031700e+04, 7.035200e+04, 7.032200e+04, 7.035500e+04,
       7.035400e+04, 7.032100e+04, 7.035900e+04, 7.035000e+04,
       7.034900e+04, 7.034800e+04, 7.031300e+04, 7.036100e+04,
       7.036200e+04, 7.036600e+04, 7.036400e+04, 7.033900e+04,
       7.033700e+04, 7.036300e+04, 7.033600e+04, 7.033800e+04,
       8.535160e+05, 7.037200e+04, 7.061800e+04, 7.062000e+04,
       7.061700e+04, 7.063200e+04, 7.065600e+04, 7.061600e+04,
       7.064300e+04, 7.061500e+04, 7.061300e+04, 7.061400e+04,
       7.064200e+04, 7.063100e+04, 7.061200e+04, 7.064000e+04,
       7.064100e+04, 7.063900e+04, 7.061100e+04, 7.060800e+04,
       7.060900e+04, 7.061000e+04, 7.063800e+04, 7.062900e+04,
       7.060700e+04, 7.062800e+04, 7.063300e+04, 7.063500e+04,
       7.063700e+04, 7.060600e+04, 7.063400e+04, 7.063600e+04,
       7.060500e+04, 7.059200e+04, 7.062400e+04, 7.062300e+04,
       7.060300e+04, 7.060100e+04, 7.062100e+04, 2.000431e+06,
       2.000409e+06, 2.000414e+06, 2.000430e+06, 7.588900e+04,
       7.588800e+04, 7.588400e+04, 7.588600e+04, 7.588500e+04,
       7.588300e+04, 7.588100e+04, 7.588700e+04, 7.587700e+04,
       7.588000e+04, 7.587900e+04, 7.587800e+04, 7.587100e+04,
       7.587200e+04, 7.521200e+04, 7.521100e+04, 7.521000e+04,
       7.520800e+04, 7.520900e+04, 7.553700e+04, 7.553600e+04,
       7.553500e+04, 7.520600e+04, 7.520700e+04, 7.515900e+04,
       7.506000e+04, 7.519000e+04, 7.518900e+04, 7.518800e+04,
       7.518700e+04, 7.515600e+04, 7.518600e+04, 7.520200e+04,
       7.517900e+04, 7.510200e+04, 7.515500e+04, 7.518000e+04,
       7.518500e+04, 7.517200e+04, 7.553200e+04, 7.517800e+04,
       7.517700e+04, 7.520500e+04, 7.520100e+04, 7.553000e+04,
       7.520000e+04, 7.520400e+04, 7.517400e+04, 7.519900e+04,
       7.517600e+04, 7.518300e+04, 7.516800e+04, 7.518200e+04,
       7.516900e+04, 7.552900e+04, 7.511700e+04, 7.553100e+04,
       7.552800e+04, 7.519600e+04, 7.519500e+04, 7.552600e+04,
       7.519800e+04, 7.519700e+04, 7.516700e+04, 7.516600e+04,
       7.519300e+04, 7.519400e+04, 7.516000e+04, 7.516100e+04,
       7.514400e+04, 7.519100e+04, 7.553400e+04, 7.553300e+04,
       7.517300e+04, 7.518100e+04, 7.519200e+04, 7.511900e+04,
       7.552400e+04, 7.552500e+04, 7.516500e+04, 7.509500e+04,
       7.510400e+04, 7.515400e+04, 7.513900e+04, 7.517100e+04,
       7.514700e+04, 7.514800e+04, 7.518400e+04, 7.517000e+04,
       7.511100e+04, 7.512000e+04, 7.511800e+04, 7.510900e+04,
       7.512100e+04, 7.509900e+04, 7.552300e+04, 7.511600e+04,
       7.510700e+04, 7.511400e+04, 7.516400e+04, 7.513100e+04,
       7.513200e+04, 7.516200e+04, 7.512500e+04, 7.512800e+04,
       7.516300e+04, 7.512600e+04, 4.207000e+04, 4.205600e+04,
       4.205500e+04, 4.207800e+04, 4.206900e+04, 4.206600e+04,
       4.206400e+04, 4.207700e+04, 4.206500e+04, 4.206800e+04,
       4.207600e+04, 4.206300e+04, 4.206200e+04, 4.207500e+04,
       4.207400e+04, 4.206000e+04, 8.293000e+03, 4.207200e+04,
       4.205900e+04, 4.207300e+04, 4.205700e+04, 4.205800e+04,
       4.207100e+04, 4.208400e+04, 4.205400e+04, 4.205200e+04,
       4.203900e+04, 4.205300e+04, 4.203700e+04, 4.204900e+04,
       4.203600e+04, 4.206100e+04, 4.203200e+04, 4.203300e+04,
       4.204500e+04, 4.203100e+04, 4.204400e+04, 7.091200e+04,
       7.091700e+04, 7.090900e+04, 7.091600e+04, 7.090500e+04,
       7.090600e+04, 7.091400e+04, 7.091100e+04, 7.090300e+04,
       7.091000e+04, 7.090100e+04, 7.091300e+04, 7.090000e+04,
       8.536380e+05, 7.090800e+04, 7.090700e+04, 7.091500e+04,
       7.090400e+04, 7.090200e+04, 1.070400e+04, 1.070300e+04,
       1.071500e+04, 3.105200e+04, 1.024900e+04, 7.122800e+04,
       7.124500e+04, 7.124700e+04, 7.124600e+04, 7.134400e+04,
       7.125100e+04, 7.123400e+04, 7.124000e+04, 7.128600e+04,
       1.085400e+04, 1.084800e+04, 9.843000e+03, 7.075100e+04,
       7.517500e+04, 7.121700e+04, 7.120300e+04, 7.122100e+04])

In [44]:
df.groupby('prod_id')['piece_count'].unique() # this thing works

prod_id
630.0           [1.0]
2304.0          [1.0]
7280.0          [2.0]
7281.0          [2.0]
7499.0         [24.0]
               ...
853638.0       [61.0]
2000409.0    [4900.0]
2000414.0     [219.0]
2000430.0    [2631.0]
2000431.0    [2455.0]
Name: piece_count, Length: 744, dtype: object

In [42]:
type(df.groupby('prod_id')['piece_count'].unique()) # what type?

pandas.core.series.Series

In [30]:
df.groupby('prod_id')['piece_count'].unique().sum() # summing

array([319071., 319073.])

In [31]:
type(df.groupby('prod_id')['piece_count'].unique().sum()) # type of the output

numpy.ndarray

In [49]:
df.groupby('prod_id')['piece_count'].unique().sum()[1] # slicing

319073.0

- by converting to list

In [101]:
df.groupby('prod_id')['piece_count'].unique().to_list()

[array([1.]),
 array([1.]),
 array([2.]),
 array([2.]),
 array([24.]),
 array([8.]),
 array([10.]),
 array([1.]),
 array([4295.]),
 array([1334.]),
 array([1077.]),
 array([2469.]),
 array([2262.]),
 array([2464.]),
 array([898.]),
 array([2382.]),
 array([1167.]),
 array([4163.]),
 array([734.]),
 array([4002.]),
 array([5923.]),
 array([2670.]),
 array([1686.]),
 array([902.]),
 array([2480.]),
 array([52.]),
 array([134.]),
 array([65.]),
 array([29.]),
 array([26.]),
 array([24.]),
 array([39.]),
 array([13.]),
 array([28.]),
 array([12.]),
 array([25.]),
 array([137.]),
 array([221.]),
 array([303.]),
 array([303.]),
 array([484.]),
 array([790.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([502.]),
 array([900.]),
 array([78.]),
 array([55.]),
 array([66.]),
 array([60.]),
 array([213.]),
 array([1.]),
 array([442.]),
 array([63.]),
 array([92.]),
 array([70.]),
 array([172.]),
 array([58.]),
 array([47.]),
 array([59.]),
 array([75.]),
 array([62.]),
 array([175.]),
 array([90.]),
 array([94.]),
 array([63.]),
 array([67.]),
 array([108.]),
 array([110.]),
 array([95.]),
 array([116.]),
 array([191.]),
 array([266.]),
 array([100.]),
 array([143.]),
 array([67.]),
 array([115.]),
 array([73.]),
 array([115.]),
 array([151.]),
 array([125.]),
 array([131.]),
 array([84.]),
 array([85.]),
 array([150.]),
 array([95.]),
 array([149.]),
 array([178.]),
 array([13.]),
 array([86.]),
 array([163.]),
 array([13.]),
 array([15.]),
 array([26.]),
 array([67.]),
 array([36.]),
 array([70.]),
 array([29.]),
 array([110.]),
 array([30.]),
 array([28.]),
 array([48.]),
 array([30.]),
 array([19.]),
 array([19.]),
 array([39.]),
 array([57.]),
 array([69.]),
 array([98.]),
 array([45.]),
 array([15.]),
 array([32.]),
 array([106.]),
 array([61.]),
 array([15.]),
 array([70.]),
 array([24.]),
 array([28.]),
 array([23.]),
 array([80.]),
 array([10.]),
 array([8.]),
 array([6.]),
 array([7.]),
 array([120.]),
 array([56.]),
 array([23.]),
 array([31.]),
 array([18.]),
 array([6.]),
 array([6.]),
 array([28.]),
 array([41.]),
 array([34.]),
 array([71.]),
 array([70.]),
 array([26.]),
 array([59.]),
 array([104.]),
 array([16.]),
 array([29.]),
 array([38.]),
 array([19.]),
 array([37.]),
 array([24.]),
 array([22.]),
 array([847.]),
 array([321.]),
 array([598.]),
 array([780.]),
 array([1032.]),
 array([361.]),
 array([444.]),
 array([468.]),
 array([744.]),
 array([386.]),
 array([597.]),
 array([219.]),
 array([519.]),
 array([571.]),
 array([208.]),
 array([559.]),
 array([706.]),
 array([318.]),
 array([247.]),
 array([387.]),
 array([729.]),
 array([717.]),
 array([1122.]),
 array([2863.]),
 array([69.]),
 array([84.]),
 array([198.]),
 array([241.]),
 array([278.]),
 array([470.]),
 array([549.]),
 array([773.]),
 array([496.]),
 array([1969.]),
 array([2049.]),
 array([231.]),
 array([962.]),
 array([230.]),
 array([132.]),
 array([286.]),
 array([124.]),
 array([222.]),
 array([230.]),
 array([326.]),
 array([528.]),
 array([792.]),
 array([122.]),
 array([102.]),
 array([174.]),
 array([194.]),
 array([246.]),
 array([205.]),
 array([275.]),
 array([359.]),
 array([285.]),
 array([356.]),
 array([386.]),
 array([728.]),
 array([670.]),
 array([109.]),
 array([109.]),
 array([223.]),
 array([241.]),
 array([225.]),
 array([200.]),
 array([379.]),
 array([374.]),
 array([422.]),
 array([601.]),
 array([249.]),
 array([140.]),
 array([126.]),
 array([115.]),
 array([80.]),
 array([174.]),
 array([77.]),
 array([286.]),
 array([575.]),
 array([174.]),
 array([195.]),
 array([1124.]),
 array([176.]),
 array([774.]),
 array([186.]),
 array([61.]),
 array([75.]),
 array([222.]),
 array([350.]),
 array([153.]),
 array([701.]),
 array([205.]),
 array([307.]),
 array([104.]),
 array([322.]),
 array([380.]),
 array([585.]),
 array([125.]),
 array([67.]),
 array([226.]),
 array([339.]),
 array([637.]),
 array([145.]),
 array([460.]),
 array([695.]),
 array([149.]),
 array([205.]),
 array([360.]),
 array([451.]),
 array([646.]),
 array([206.]),
 array([217.]),
 array([712.]),
 array([145.]),
 array([142.]),
 array([351.]),
 array([432.]),
 array([1078.]),
 array([185.]),
 array([145.]),
 array([45.]),
 array([62.]),
 array([79.]),
 array([86.]),
 array([185.]),
 array([289.]),
 array([328.]),
 array([589.]),
 array([622.]),
 array([186.]),
 array([309.]),
 array([603.]),
 array([871.]),
 array([246.]),
 array([370.]),
 array([307.]),
 array([402.]),
 array([585.]),
 array([326.]),
 array([217.]),
 array([86.]),
 array([95.]),
 array([163.]),
 array([119.]),
 array([210.]),
 array([223.]),
 array([229.]),
 array([351.]),
 array([378.]),
 array([460.]),
 array([488.]),
 array([722.]),
 array([91.]),
 array([127.]),
 array([102.]),
 array([89.]),
 array([91.]),
 array([99.]),
 array([101.]),
 array([151.]),
 array([96.]),
 array([143.]),
 array([93.]),
 array([109.]),
 array([118.]),
 array([139.]),
 array([116.]),
 array([708.]),
 array([122.]),
 array([143.]),
 array([135.]),
 array([108.]),
 array([119.]),
 array([130.]),
 array([101.]),
 array([105.]),
 array([113.]),
 array([136.]),
 array([141.]),
 array([149.]),
 array([209.]),
 array([240.]),
 array([160.]),
 array([234.]),
 array([155.]),
 array([252.]),
 array([125.]),
 array([375.]),
 array([494.]),
 array([1219.]),
 array([113.]),
 array([180.]),
 array([476.]),
 array([1043.]),
 array([1166.]),
 array([1977.]),
 array([3929.]),
 array([2704.]),
 array([199.]),
 array([140.]),
 array([142.]),
 array([365.]),
 array([260.]),
 array([631.]),
 array([603.]),
 array([1327.]),
 array([370.]),
 array([1151.]),
 array([1098.]),
 array([2382.]),
 array([1862.]),
 array([171.]),
 array([135.]),
 array([139.]),
 array([330.]),
 array([513.]),
 array([1020.]),
 array([1005.]),
 array([2595.]),
 array([176.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([7.]),
 array([1.]),
 array([610.]),
 array([888.]),
 array([81.]),
 array([157.]),
 array([90.]),
 array([214.]),
 array([257.]),
 array([412.]),
 array([919.]),
 array([250.]),
 array([301.]),
 array([83.]),
 array([175.]),
 array([324.]),
 array([330.]),
 array([824.]),
 array([1277.]),
 array([200.]),
 array([157.]),
 array([47.]),
 array([80.]),
 array([144.]),
 array([294.]),
 array([374.]),
 array([561.]),
 array([894.]),
 array([138.]),
 array([403.]),
 array([81.]),
 array([91.]),
 array([239.]),
 array([249.]),
 array([169.]),
 array([337.]),
 array([248.]),
 array([53.]),
 array([88.]),
 array([201.]),
 array([378.]),
 array([426.]),
 array([813.]),
 array([1250.]),
 array([76.]),
 array([141.]),
 array([347.]),
 array([415.]),
 array([792.]),
 array([195.]),
 array([740.]),
 array([37.]),
 array([88.]),
 array([297.]),
 array([303.]),
 array([663.]),
 array([387.]),
 array([126.]),
 array([87.]),
 array([78.]),
 array([190.]),
 array([192.]),
 array([174.]),
 array([344.]),
 array([310.]),
 array([82.]),
 array([127.]),
 array([294.]),
 array([883.]),
 array([187.]),
 array([1140.]),
 array([516.]),
 array([670.]),
 array([69.]),
 array([75.]),
 array([64.]),
 array([67.]),
 array([98.]),
 array([216.]),
 array([208.]),
 array([266.]),
 array([840.]),
 array([393.]),
 array([598.]),
 array([1426.]),
 array([251.]),
 array([257.]),
 array([153.]),
 array([79.]),
 array([66.]),
 array([80.]),
 array([88.]),
 array([83.]),
 array([10.]),
 array([439.]),
 array([221.]),
 array([294.]),
 array([754.]),
 array([109.]),
 array([233.]),
 array([312.]),
 array([341.]),
 array([341.]),
 array([494.]),
 array([544.]),
 array([747.]),
 array([876.]),
 array([944.]),
 array([914.]),
 array([1403.]),
 array([2295.]),
 array([4867.]),
 array([83.]),
 array([360.]),
 array([313.]),
 array([48.]),
 array([217.]),
 array([521.]),
 array([1202.]),
 array([61.]),
 array([69.]),
 array([68.]),
 array([69.]),
 array([73.]),
 array([257.]),
 array([308.]),
 array([530.]),
 array([552.]),
 array([556.]),
 array([765.]),
 array([830.]),
 array([2028.]),
 array([124.]),
 array([201.]),
 array([139.]),
 array([254.]),
 array([448.]),
 array([581.]),
 array([433.]),
 array([460.]),
 array([775.]),
 array([1047.]),
 array([204.]),
 array([305.]),
 array([1628.]),
 array([141.]),
 array([366.]),
 array([564.]),
 array([1053.]),
 array([1456.]),
 array([198.]),
 array([267.]),
 array([293.]),
 array([425.]),
 array([3444.]),
 array([643.]),
 array([7.]),
 array([8.]),
 array([8.]),
 array([7.]),
 array([4080.]),
 array([2294.]),
 array([267.]),
 array([85.]),
 array([45.]),
 array([39.]),
 array([38.]),
 array([115.]),
 array([92.]),
 array([59.]),
 array([58.]),
 array([96.]),
 array([40.]),
 array([52.]),
 array([259.]),
 array([102.]),
 array([96.]),
 array([119.]),
 array([76.]),
 array([73.]),
 array([105.]),
 array([156.]),
 array([46.]),
 array([118.]),
 array([55.]),
 array([56.]),
 array([56.]),
 array([57.]),
 array([93.]),
 array([64.]),
 array([56.]),
 array([217.]),
 array([191.]),
 array([369.]),
 array([506.]),
 array([569.]),
 array([604.]),
 array([1996.]),
 array([1685.]),
 array([193.]),
 array([717.]),
 array([1005.]),
 array([85.]),
 array([83.]),
 array([160.]),
 array([81.]),
 array([98.]),
 array([86.]),
 array([82.]),
 array([104.]),
 array([169.]),
 array([106.]),
 array([87.]),
 array([91.]),
 array([93.]),
 array([112.]),
 array([88.]),
 array([409.]),
 array([1703.]),
 array([558.]),
 array([530.]),
 array([543.]),
 array([659.]),
 array([863.]),
 array([4016.]),
 array([109.]),
 array([88.]),
 array([90.]),
 array([78.]),
 array([120.]),
 array([112.]),
 array([117.]),
 array([125.]),
 array([262.]),
 array([208.]),
 array([269.]),
 array([419.]),
 array([691.]),
 array([149.]),
 array([277.]),
 array([358.]),
 array([294.]),
 array([554.]),
 array([457.]),
 array([630.]),
 array([836.]),
 array([1966., 1967.]),
 array([305.]),
 array([282.]),
 array([309.]),
 array([557.]),
 array([775.]),
 array([1106.]),
 array([780.]),
 array([1376.]),
 array([1416.]),
 array([825.]),
 array([7541.]),
 array([92.]),
 array([91.]),
 array([216.]),
 array([188.]),
 array([108.]),
 array([97.]),
 array([157.]),
 array([241.]),
 array([370.]),
 array([746.]),
 array([278.]),
 array([376.]),
 array([102.]),
 array([99.]),
 array([229.]),
 array([345.]),
 array([464.]),
 array([519.]),
 array([1413., 1414.]),
 array([89.]),
 array([87.]),
 array([148.]),
 array([94.]),
 array([85.]),
 array([92.]),
 array([179.]),
 array([100.]),
 array([452.]),
 array([144.]),
 array([168.]),
 array([101.]),
 array([101.]),
 array([104.]),
 array([74.]),
 array([168.]),
 array([277.]),
 array([4634.]),
 array([556.]),
 array([185.]),
 array([166.]),
 array([196.]),
 array([181.]),
 array([184.]),
 array([161.]),
 array([366.]),
 array([941.]),
 array([183.]),
 array([203.]),
 array([179.]),
 array([163.]),
 array([391.]),
 array([841.]),
 array([126.]),
 array([222.]),
 array([397.]),
 array([577.]),
 array([1019.]),
 array([289.]),
 array([360.]),
 array([609.]),
 array([174.]),
 array([92.]),
 array([91.]),
 array([306.]),
 array([2526.]),
 array([563.]),
 array([759.]),
 array([257.]),
 array([358.]),
 array([330.]),
 array([93.]),
 array([83.]),
 array([85.]),
 array([79.]),
 array([94.]),
 array([85.]),
 array([286.]),
 array([160.]),
 array([377.]),
 array([375.]),
 array([197.]),
 array([323.]),
 array([185.]),
 array([375.]),
 array([400.]),
 array([197.]),
 array([622.]),
 array([955.]),
 array([492.]),
 array([89.]),
 array([86.]),
 array([79.]),
 array([199.]),
 array([406.]),
 array([271.]),
 array([229.]),
 array([358.]),
 array([124.]),
 array([223.]),
 array([416.]),
 array([375.]),
 array([1363.]),
 array([674.]),
 array([1004.]),
 array([30.]),
 array([61.]),
 array([4900.]),
 array([219.]),
 array([2631.]),
 array([2455.])]

In [103]:
ss = df.groupby('prod_id')['piece_count'].unique().to_list()

In [106]:
sum(ss)

array([319071., 319073.])

- by converting to df

In [71]:
x = df.groupby('prod_id')['piece_count'].unique().to_frame().reset_index()
x#['piece_count'].sum()

       prod_id piece_count
0        630.0       [1.0]
1       2304.0       [1.0]
2       7280.0       [2.0]
3       7281.0       [2.0]
4       7499.0      [24.0]
..         ...         ...
739   853638.0      [61.0]
740  2000409.0    [4900.0]
741  2000414.0     [219.0]
742  2000430.0    [2631.0]
743  2000431.0    [2455.0]

[744 rows x 2 columns]

In [91]:
x = x.drop(columns = 'prod_id')

KeyError: "['prod_id'] not found in axis"

In [77]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   piece_count  744 non-null    object
dtypes: object(1)
memory usage: 5.9+ KB

In [78]:
x.sum()

piece_count    [319071.0, 319073.0]
dtype: object

- another way

In [108]:
df.groupby('prod_id').mean().piece_count.sum().round(0)

319071.0

Now, let's try getting the value for the 90% quantile for all numerical columns.  Do this in the cell below.

In [33]:
# Get the 90% quantile for all numerical columns
df.quantile(q=.9)

list_price            136.2971
num_reviews            38.0000
piece_count          1077.0000
play_star_rating        5.0000
prod_id             75531.0000
star_rating             5.0000
val_star_rating         5.0000
Name: 0.9, dtype: float64

## Getting Summary Statistics on Categorical Data

For obvious reasons, most of the methods we've used so far only work with numerical data -- there's no way to calculate the standard deviation of a column containing string values. However, there are some things that we can discover about columns containing categorical data. 

In the cell below, print the unique values contained within the `review_difficulty` column.

In [66]:
# Print the unique values in the review_difficulty column
df['review_difficulty'].unique()

array(['Average', 'Easy', 'Challenging', 'Very Easy', nan,
       'Very Challenging'], dtype=object)

Now, let's get the `value_counts()` for this column, to see how common each is.

In [67]:
# Get the value_counts() of the review_difficulty column
df['review_difficulty'].value_counts()

Easy                4236
Average             3765
Very Easy           1139
Challenging         1058
Very Challenging       8
Name: review_difficulty, dtype: int64

As you can see, these provide us quick and easy ways to get information on columns containing categorical information.  


## Using `.applymap()`

When working with pandas DataFrames, we can quickly compute functions on the data contained by using the `.applymap()` method and passing in a lambda function. 

For instance, we can use `applymap()` to return a version of the DataFrame where every value has been converted to a string.

In the cell below:

* Call the DataFrame's `.applymap()` method and pass in `lambda x: str(x)`  
* Call the new `string_df` object's `.info()` method to confirm that everything has been cast to a string

In [68]:
# Call the .applymap() method
string_df = df.applymap(lambda x: str(x))

# Call the .info() method
string_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ages               12261 non-null  object
 1   list_price         12261 non-null  object
 2   num_reviews        12261 non-null  object
 3   piece_count        12261 non-null  object
 4   play_star_rating   12261 non-null  object
 5   prod_desc          12261 non-null  object
 6   prod_id            12261 non-null  object
 7   prod_long_desc     12261 non-null  object
 8   review_difficulty  12261 non-null  object
 9   set_name           12261 non-null  object
 10  star_rating        12261 non-null  object
 11  theme_name         12261 non-null  object
 12  val_star_rating    12261 non-null  object
 13  country            12261 non-null  object
dtypes: object(14)
memory usage: 1.3+ MB

Note that everything -- even the `NaN` values, have been cast to a string in the example above. 

Note that for Pandas Series objects (such as a single column in a DataFrame), we can do the same thing using the `.apply()` method.  

This is just one example of how we can quickly compute custom functions on our DataFrame -- this will become especially useful when we learn how to **_normalize_** our datasets in a later section!

## Summary

In this lab, we learned how to:

* Use the `df.describe()` and `df.info()` summary statistics methods 
* Use built-in Pandas methods for calculating summary statistics 
* Apply a function to every element in a DataFrame